package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/spf13/cobra"
)

const entityTemplate = `package entities

import (
	"awo.so/framework/internal/core"
	"awo.so/framework/pkg/entitydef"
	"awo.so/framework/pkg/fieldtype"
	"awo.so/framework/pkg/permissions"
)

// {{.Name}}Definition declares the {{.Name}} entity.
// Generated by: awo scaffold entity {{.Name}} --type={{.Type}}
// Date: {{.Date}}
//
// Edit this file to add fields, hooks, permissions, and workflow bindings.
var {{.Name}}Definition = entitydef.New("{{.Name}}").
	Label("{{.Label}}").
	Field("name", fieldtype.Data, fieldtype.Required(), fieldtype.MaxLen(255)).
	Allow(permissions.Grant("admin", permissions.AllActions...)).
	MustBuild()

// Register adds {{.Name}} to the given registry. Call this from your module's Register function.
func Register{{.Name}}(reg *core.EntityRegistry) {
	reg.MustRegister({{.Name}}Definition)
}
`

type scaffoldData struct {
	Name  string
	Label string
	Type  string
	Date  string
}

func scaffoldCmd() *cobra.Command {
	var entityType string

	cmd := &cobra.Command{
		Use:   "scaffold entity <Name>",
		Short: "Scaffold a new EntityDefinition",
		Args:  cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			if args[0] != "entity" {
				return fmt.Errorf("unknown scaffold target %q (only 'entity' is supported)", args[0])
			}
			name := args[1]
			if name == "" {
				return fmt.Errorf("entity name must not be empty")
			}

			label := toLabel(name)
			data := scaffoldData{
				Name:  name,
				Label: label,
				Type:  entityType,
				Date:  time.Now().Format("2006-01-02"),
			}

			outDir := filepath.Join("entities")
			if err := os.MkdirAll(outDir, 0o755); err != nil {
				return fmt.Errorf("create output dir: %w", err)
			}

			outFile := filepath.Join(outDir, strings.ToLower(name)+".go")
			f, err := os.Create(outFile)
			if err != nil {
				return fmt.Errorf("create file: %w", err)
			}
			defer f.Close()

			tmpl, err := template.New("entity").Parse(entityTemplate)
			if err != nil {
				return err
			}
			if err := tmpl.Execute(f, data); err != nil {
				return err
			}

			fmt.Printf("scaffolded: %s\n", outFile)
			return nil
		},
	}

	cmd.Flags().StringVar(&entityType, "type", "custom", "Entity type: system or custom")
	return cmd
}

// toLabel converts PascalCase to "Title Case".
func toLabel(name string) string {
	var b strings.Builder
	for i, r := range name {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteRune(' ')
		}
		b.WriteRune(r)
	}
	return b.String()
}
